# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zmc/Downloads/V-REP_PRO_EDU_V3_5_0_Linux/Vrep-camera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zmc/Downloads/V-REP_PRO_EDU_V3_5_0_Linux/Vrep-camera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zmc/Downloads/V-REP_PRO_EDU_V3_5_0_Linux/Vrep-camera/CMakeFiles /home/zmc/Downloads/V-REP_PRO_EDU_V3_5_0_Linux/Vrep-camera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zmc/Downloads/V-REP_PRO_EDU_V3_5_0_Linux/Vrep-camera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named VrepCamera.bin

# Build rule for target.
VrepCamera.bin: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 VrepCamera.bin
.PHONY : VrepCamera.bin

# fast build rule for target.
VrepCamera.bin/fast:
	$(MAKE) -f CMakeFiles/VrepCamera.bin.dir/build.make CMakeFiles/VrepCamera.bin.dir/build
.PHONY : VrepCamera.bin/fast

#=============================================================================
# Target rules for targets named simdata.lib

# Build rule for target.
simdata.lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simdata.lib
.PHONY : simdata.lib

# fast build rule for target.
simdata.lib/fast:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/build
.PHONY : simdata.lib/fast

src/connect.o: src/connect.cpp.o

.PHONY : src/connect.o

# target to build an object file
src/connect.cpp.o:
	$(MAKE) -f CMakeFiles/VrepCamera.bin.dir/build.make CMakeFiles/VrepCamera.bin.dir/src/connect.cpp.o
.PHONY : src/connect.cpp.o

src/connect.i: src/connect.cpp.i

.PHONY : src/connect.i

# target to preprocess a source file
src/connect.cpp.i:
	$(MAKE) -f CMakeFiles/VrepCamera.bin.dir/build.make CMakeFiles/VrepCamera.bin.dir/src/connect.cpp.i
.PHONY : src/connect.cpp.i

src/connect.s: src/connect.cpp.s

.PHONY : src/connect.s

# target to generate assembly for a file
src/connect.cpp.s:
	$(MAKE) -f CMakeFiles/VrepCamera.bin.dir/build.make CMakeFiles/VrepCamera.bin.dir/src/connect.cpp.s
.PHONY : src/connect.cpp.s

src/extApi.o: src/extApi.c.o

.PHONY : src/extApi.o

# target to build an object file
src/extApi.c.o:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApi.c.o
.PHONY : src/extApi.c.o

src/extApi.i: src/extApi.c.i

.PHONY : src/extApi.i

# target to preprocess a source file
src/extApi.c.i:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApi.c.i
.PHONY : src/extApi.c.i

src/extApi.s: src/extApi.c.s

.PHONY : src/extApi.s

# target to generate assembly for a file
src/extApi.c.s:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApi.c.s
.PHONY : src/extApi.c.s

src/extApiPlatform.o: src/extApiPlatform.c.o

.PHONY : src/extApiPlatform.o

# target to build an object file
src/extApiPlatform.c.o:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApiPlatform.c.o
.PHONY : src/extApiPlatform.c.o

src/extApiPlatform.i: src/extApiPlatform.c.i

.PHONY : src/extApiPlatform.i

# target to preprocess a source file
src/extApiPlatform.c.i:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApiPlatform.c.i
.PHONY : src/extApiPlatform.c.i

src/extApiPlatform.s: src/extApiPlatform.c.s

.PHONY : src/extApiPlatform.s

# target to generate assembly for a file
src/extApiPlatform.c.s:
	$(MAKE) -f CMakeFiles/simdata.lib.dir/build.make CMakeFiles/simdata.lib.dir/src/extApiPlatform.c.s
.PHONY : src/extApiPlatform.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... VrepCamera.bin"
	@echo "... edit_cache"
	@echo "... simdata.lib"
	@echo "... src/connect.o"
	@echo "... src/connect.i"
	@echo "... src/connect.s"
	@echo "... src/extApi.o"
	@echo "... src/extApi.i"
	@echo "... src/extApi.s"
	@echo "... src/extApiPlatform.o"
	@echo "... src/extApiPlatform.i"
	@echo "... src/extApiPlatform.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

